#!/usr/bin/env bash
# This script configures a new Ubuntu server to set up Nginx, add a redirection, and customize the 404 page.

apt-get -y update
apt-get install -y nginx

# Set up the content for the homepage and custom 404 page
echo "Holberton School for the win!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx to handle the redirection and custom 404
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm 404.html index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$HOSTNAME;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=-VGIt10m9VQ;
    }
    error_page 404 /404.html;
    location /xyz {
        return 404;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx to apply changes
sudo service nginx restart
sudo service nginx reload

