#!/usr/bin/env bash
#This script installs nginx and makes sure it litsens to port 80

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
