#!/usr/bin/env bash
#This script installs Nginix on the server and configures it to server a specific  homepage 

sudo apt-get update
sudo apt-get -y install nginx

echo "Holberton School for the win!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

sudo service nginx restart

