#!/usr/bin/env bash
# This script configures a new Ubuntu machine with Nginx and a custom 404 error page.

sudo apt-get update
sudo apt-get install -y nginx

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

echo "server {
    listen 80;
    root /var/www/html;
    index index.html index.htm;

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx restart

